version: '3.9'

services:

  nosqldata:
    image: mongo

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile

  logging.api:
    image: ${DOCKER_REGISTRY-}loggingapi
    build:
      context: .
      dockerfile: src/Services/Logging/Logging.API/Dockerfile


  routes.api:
    image: ${DOCKER_REGISTRY-}routesapi
    build:
      context: .
      dockerfile: src/Services/Route/Routes.API/Dockerfile


  teams.api:
    image: ${DOCKER_REGISTRY-}teamsapi
    build:
      context: .
      dockerfile: src/Services/Team/Teams.API/Dockerfile


  apigateway.ocelot:
    image: ${DOCKER_REGISTRY-}apigatewayocelot
    build:
      context: .
      dockerfile: src/ApiGateway/ApiGateway.Ocelot/Dockerfile

